In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)
players_df = pd.read_csv('players.csv')

In [27]:
df = pd.read_csv('team_completed_df.csv')

In [28]:
df2 = df[['team_1','team_2','map_winner']]

In [29]:
df2

team_1        team_2  map_winner
0             Legacy      Corvidae           1
1          Athletico  Alpha Sydney           2
2          Athletico  Alpha Sydney           1
3             Cypher      Corvidae           1
4      Funky Monkeys  Alpha Sydney           2
...              ...           ...         ...
17340        Rugratz       Recon 5           2
17341       Under 21         Chaos           2
17342  Thunder Logic      Station7           2
17343        Oceanus        Divine           2
17344         Chiefs      Airborne           1

[17345 rows x 3 columns]

In [77]:
# Used to find the difference between team_1 and team_2 stat features

#df2['kast'] = df2['1_kast']-df2['2_kast']
#df2['adr'] = df2['1_adr']-df2['2_adr']
#df2['KPR'] = df2['1_KPR']-df2['2_KPR']
#df2['SPR'] = df2['1_SPR']-df2['2_SPR']
#df2['DPR'] = df2['1_DPR']-df2['2_DPR']
#df2['APR'] = df2['1_APR']-df2['2_APR']

In [10]:
# Top CSGO Teams
teams = ['AGO', 'forZe', 'AVANGAR', 'HAVU', 'Heroic', 'FURIA', 'Sprout',
       'Spirit', 'Tricked', 'Windigo', 'Astralis', 'Liquid', 'TYLOO', 'FaZe',
       'ALTERNATE aTTaX', 'Virtus.pro', 'Natus Vincere', 'North', 'NRG',
       'Chiefs', 'ORDER', 'Renegades', 'Nemiga', 'mousesports', 'Valiance',
       'G2', 'Singularity', 'ENCE', 'eUnited', 'LDLC', 'Grayhound',
       'Complexity', 'BIG', 'DETONA', 'fnatic', 'NiP', 'SJ', 'HellRaisers',
       'OpTic', 'Vitality', 'pro100', 'TeamOne', 'Cloud9', 'W7M',
       'Movistar Riders', 'Epsilon', 'Chaos', 'PACT', 'MIBR', 'DreamEaters','Kinguin','Gambit']

In [31]:
# Finds games with only a top CSGO team in it
teams_1 = df2[df2['team_1'].isin(teams)]
teams_2 = df2[df2['team_2'].isin(teams)]
df2 = pd.concat((teams_1,teams_2))
df2.drop_duplicates()
df2

team_1           team_2  map_winner
26         Kinguin             Envy           2
27     mousesports               G2           1
28     mousesports               G2           2
29      Virtus.pro              NiP           1
30      Virtus.pro              NiP           1
...            ...              ...         ...
17334       pro100           Nemiga           2
17335         PACT  Movistar Riders           1
17338         PACT             HAVU           2
17339  HellRaisers             HAVU           1
17341     Under 21            Chaos           2

[13902 rows x 3 columns]

In [32]:
# Converts team names it seperate categorical columns(team name columns)
final = pd.get_dummies(df2, columns=['team_1','team_2'])

In [33]:
# Features for model
X = final.copy()
X = final.drop('map_winner', axis=1)
X

team_1_100 Thieves  team_1_3DMAX  team_1_5POWER  team_1_5balls  \
26                      0             0              0              0   
27                      0             0              0              0   
28                      0             0              0              0   
29                      0             0              0              0   
30                      0             0              0              0   
...                   ...           ...            ...            ...   
17334                   0             0              0              0   
17335                   0             0              0              0   
17338                   0             0              0              0   
17339                   0             0              0              0   
17341                   0             0              0              0   

       team_1_9z  team_1_AGF  team_1_AGO  team_1_ALTERNATE aTTaX  team_1_ARCY  \
26             0           0           0                       0            0   
27             0           0           0                       0            0   
28             0           0           0                       0            0   
29             0           0           0                       0            0   
30             0           0           0                       0            0   
...          ...         ...         ...                     ...          ...   
17334          0           0           0                       0            0   
17335          0           0           0                       0            0   
17338          0           0           0                       0            0   
17339          0           0           0                       0            0   
17341          0           0           0                       0            0   

       team_1_ATK  team_1_AUGUST  team_1_AVANGAR  team_1_AVANT  team_1_AVEZ  \
26              0              0               0             0            0   
27              0              0               0             0            0   
28              0              0               0             0            0   
29              0              0               0             0            0   
30              0              0               0             0            0   
...           ...            ...             ...           ...          ...   
17334           0              0               0             0            0   
17335           0              0               0             0            0   
17338           0              0               0             0            0   
17339           0              0               0             0            0   
17341           0              0               0             0            0   

       team_1_AWTR  team_1_All Knights  team_1_Alpha Red  team_1_Ambush  \
26               0                   0                 0              0   
27               0                   0                 0              0   
28               0                   0                 0              0   
29               0                   0                 0              0   
30               0                   0                 0              0   
...            ...                 ...               ...            ...   
17334            0                   0                 0              0   
17335            0                   0                 0              0   
17338            0                   0                 0              0   
17339            0                   0                 0              0   
17341            0                   0                 0              0   

       team_1_Ancient  team_1_Ardeont Academy  team_1_Aristocracy  \
26                  0                       0                   0   
27                  0                       0                   0   
28                  0                       0                   0   
29                  0          

In [34]:
# target map_winner
y = final['map_winner'].values
y[:5]

array([2, 1, 2, 1, 1], dtype=int64)

In [35]:
# splitting training and testing data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, train_size=0.80)

In [36]:
# training linear logistic regression model
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(X, y)

LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
# Creating model statistics
p_pred = model.predict_proba(X)
y_pred = model.predict(X)
score_ = model.score(X, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [39]:
#Model Accuracy Score
score_

0.58595885484103

In [40]:
# Model confusion matrix
y_true, y_pred = y_test, model.predict(X_test)
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           1       0.60      0.71      0.65      1451
           2       0.60      0.47      0.53      1330

    accuracy                           0.60      2781
   macro avg       0.60      0.59      0.59      2781
weighted avg       0.60      0.60      0.59      2781



In [45]:
# Example prediction for future match
model.predict(predict_final)

array([1], dtype=int64)

In [46]:
# Probability of of each prediction
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
print(p_pred)

[[0.45204831 0.54795169]
 [0.49164129 0.50835871]
 [0.49164129 0.50835871]
 [0.54596211 0.45403789]
 [0.54596211 0.45403789]
 [0.47698791 0.52301209]
 [0.5938493  0.4061507 ]
 [0.5938493  0.4061507 ]
 [0.45146458 0.54853542]
 [0.51686796 0.48313204]
 [0.59509023 0.40490977]
 [0.45087716 0.54912284]
 [0.45513039 0.54486961]
 [0.58822172 0.41177828]
 [0.4595336  0.5404664 ]
 [0.65702075 0.34297925]
 [0.50205221 0.49794779]
 [0.86293826 0.13706174]
 [0.53914398 0.46085602]
 [0.52272664 0.47727336]
 [0.39385253 0.60614747]
 [0.85908518 0.14091482]
 [0.4973755  0.5026245 ]
 [0.44470023 0.55529977]
 [0.45851396 0.54148604]
 [0.54701243 0.45298757]
 [0.52073049 0.47926951]
 [0.45691609 0.54308391]
 [0.47007464 0.52992536]
 [0.53661538 0.46338462]
 [0.45924872 0.54075128]
 [0.46390601 0.53609399]
 [0.47149777 0.52850223]
 [0.4533851  0.5466149 ]
 [0.47710886 0.52289114]
 [0.45485825 0.54514175]
 [0.45851396 0.54148604]
 [0.56837946 0.43162054]
 [0.51293067 0.48706933]
 [0.51293067 0.48706933]


In [71]:
# importing libraries
import numpy as np
from sklearn.svm import SVC
from sklearn import svm
model = svm.SVC()

In [72]:
# training SVM model
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [73]:
# Model Predictions of first 30
y_pred = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head(30)

Prediction  Actual
0            1       2
1            1       1
2            2       2
3            1       1
4            2       2
5            1       1
6            2       1
7            2       2
8            1       1
9            1       2
10           2       2
11           2       2
12           2       2
13           1       1
14           1       1
15           1       1
16           2       1
17           2       2
18           1       2
19           1       1
20           1       2
21           1       1
22           2       2
23           1       1
24           1       2
25           2       2
26           2       2
27           1       2
28           2       2
29           1       1

In [74]:
# Model Accuracy
from sklearn.metrics import accuracy_score
predicted = model.predict(X_test)
accuracy_score(y_test,predicted)

0.5376869965477561

In [76]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [77]:
# Training Model and displaying model accuracy scores for both training and test
rf = RandomForestClassifier(n_estimators=500, max_depth=60,random_state=0) 
rf.fit(X_train, y_train)
score = rf.score(X_train, y_train)
score2 = rf.score(X_test, y_test)
print(score, score2)

0.6908689813926722 0.5388377445339471


In [43]:
# Example prediction

team_1 = ['Spirit']
team_2 = ['Virtus.pro']
map_winner = [None]

predict = pd.DataFrame(list(zip(team_1,team_2,map_winner)),columns=['team_1','team_2','map_winner'])
predict_final = pd.get_dummies(predict,columns=['team_1','team_2'])
predict_final = predict_final.drop('map_winner',axis=1)
predict_final

team_1_Spirit  team_2_Virtus.pro
0              1                  1

In [44]:
missing_cols = set(X.columns) - set(predict_final.columns)
for c in missing_cols:
    predict_final[c] = 0
predict_final = predict_final[X.columns]

In [ ]:
rf.predict(predict_final)